-- 在现有 Supabase 项目的 SQL Editor 中完整运行一次。
create table if not exists public.site_messages (
  id bigint generated by default as identity primary key,
  visitor_name text,
  message_content text not null,
  created_at timestamptz not null default now(),
  constraint site_messages_name_length check (char_length(visitor_name) <= 40),
  constraint site_messages_content_length check (
    char_length(message_content) between 2 and 500
  )
);

alter table public.site_messages enable row level security;

-- 匿名访客不能直接读取或修改留言表，只能调用下方的提交函数。
revoke all on table public.site_messages from anon, authenticated;
revoke all on sequence public.site_messages_id_seq from anon, authenticated;

create or replace function public.submit_site_message(
  p_name text,
  p_content text
)
returns bigint
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  new_message_id bigint;
  clean_name text := nullif(trim(coalesce(p_name, '')), '');
  clean_content text := trim(coalesce(p_content, ''));
begin
  if char_length(clean_name) > 40 then
    raise exception 'name_too_long';
  end if;
  if char_length(clean_content) < 2 or char_length(clean_content) > 500 then
    raise exception 'invalid_message_length';
  end if;

  insert into public.site_messages (visitor_name, message_content)
  values (clean_name, clean_content)
  returning id into new_message_id;

  return new_message_id;
end;
$$;

revoke all on function public.submit_site_message(text, text) from public;
grant execute on function public.submit_site_message(text, text) to anon, authenticated;
